GMAIL_IMAP_SERVER = 'imap.gmail.com'
LOGGER_SUBJECT_MAX_LENGTH = 10
DEFAULT_MAX_ATTRIBUTE_LENGTH = 100
DEFAULT_SPAM_THRESHOLD = 8
DEFAULT_LOG_LEVEL = 0
DEFAULT_OPENAI_BASE_URL = 'https://api.openai.com/v1'
DB_FILE_NAME = 'db.json'
